# Generated by Django 2.0.2 on 2018-02-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180225_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='mMZ1EqM1', max_length=8, unique=True),
        ),
    ]
