# Generated by Django 2.0.2 on 2018-02-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180219_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='guest-user.png', upload_to='ProfilePic'),
        ),
    ]
